kind: Deployment
apiVersion: apps/v1
metadata:
  name: observer
  labels:
    name: observer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: observer
      role: observerapp
  template:
    spec:
      containers:
      - name: observer
        image: bencer/recurling:0.1
        env:
        - name: URL
          value: "result.demo.svc.cluster.local"
        - name: SLEEP
          value: "5"
        resources:
          limits:
            memory: 64Mi
          requests:
            memory: 32Mi
        securityContext:
          readOnlyRootFilesystem: true
    metadata:
      labels:
        name: observer
        role: observerapp
