kind: Deployment
apiVersion: apps/v1
metadata:
  name: redis
  labels:
    name: redis-deployment
  
spec:
  replicas: 1
  selector:
    matchLabels:
     name: redis
     role: redisdb
  template:
    spec:
      containers:
        - name: redis
          image: redis:alpine
          resources:
            limits:
              memory: 64Mi
            requests:
              memory: 32Mi
    metadata:
      labels:
        name: redis
        role: redisdb    
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: redis
  name: redis
  
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis
    role: redisdb