kind: Deployment
apiVersion: apps/v1
metadata:
  name: voter
  labels:
    name: voter-deployment
  
spec:
  replicas: 1
  selector:
    matchLabels:
     name: voter
     role: voterapp 
  template:
    spec:
      containers:
        - name: voter
          image: mateobur/voter:sko
          env:
            - name: VOTE
              value: "vote.demo.svc.cluster.local"
            - name: PORT
              value: "80"
          resources:
            limits:
              memory: 64Mi
            requests:
              memory: 32Mi
    metadata:
      labels:
        name: voter
        role: voterapp