kind: Deployment
apiVersion: apps/v1
metadata:
  name: worker
  labels:
    name: worker-deployment
  
spec:
  replicas: 1
  selector:
    matchLabels:
     name: worker
     role: workerapp
  template:
    spec:
      containers:
        - name: worker
          image: bencer/example-voting-app-worker:jmx-1
          resources:
            limits:
              memory: 128Mi
            requests:
              memory: 64Mi
    metadata:
      labels:
        name: worker
        role: workerapp
        